### ISSUE TITLE
Support build.gradle written in kotlin

### ISSUE THREAD

**Issue by ericbottard** [cloudfoundry/build-system-cnb#3]

**Comment by nebhale** [comment]
Do you have any reason to believe that this doesn't currently work?  If a [`build.gradle` is noticed](https://github.com/cloudfoundry/build-system-buildpack/blob/master/buildsystem/gradle.go#L45), regardless of the language within it, `gradle -x test build` is run.

**Comment by ericbottard** [comment]
See original poster repo, the file ends in .kt

**Comment by nebhale** [comment]
I checked out that post and other than the mention of `ApplicationKt`, I don't see those two letters together.  In addition, the repo linked to in the final bit of the issue [has a `build.gradle`](https://github.com/opengood-io/bank-save-transaction-function-service).  No wonder I couldn't figure it out :)
